export const DEMO_MAILER_PRODUCTION_SCENARIOS = [
  ["selling", "Selling mailer", "Available inventory is open."],
  ["reserved", "Reserved placement", "A fictional buyer holds the placement."],
  ["paid", "Paid placement", "Sample payment is complete."],
  ["missing_campaign", "No Campaign", "Candidate generation is blocked."],
  ["campaign_incomplete", "Campaign incomplete", "Campaign readiness needs work."],
  ["qr_incomplete", "QR incomplete", "Campaign-linked QR association is missing."],
  ["artwork_changes", "Artwork changes requested", "Customer correction is required."],
  ["artwork_approved", "Artwork approved", "Proof approval is complete."],
  ["preflight_blocked", "Preflight blocked", "A production blocker remains."],
  ["preflight_warning", "Warning only", "No blockers; one explicit QR contrast warning."],
  ["ready", "Ready to generate", "Locked current revision has passing preflight."],
  ["candidate_current", "Candidate current", "Fictional stored candidate matches revision 8."],
  ["candidate_stale", "Candidate stale", "Fictional candidate belongs to revision 7."],
  ["printer_certified", "Printer certified", "Authorized fictional printer confirmation recorded."],
  ["printed", "Printed", "Current certified candidate selected for print."],
  ["mailed", "Mailed", "Fictional physical delivery recorded."],
  ["published", "Published", "Digital companion is publicly available."],
] as const;
