import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Loader2, MapPin, ShoppingBag } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { AdpadzButton, AdpadzCard } from '../../components/adpadz-ui';
import { formatCurrency } from '../../lib/communityCards';

type Order = { id: string; quantity: number; amount_cents: number; status: string; created_at: string; community_cards: { title: string; zone_name: string | null; public_slug: string } | null };
export default function CommunityAdOrders() {
  const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { void (async () => { const { data, error: queryError } = await supabase.from('community_card_orders').select('id,quantity,amount_cents,status,created_at,community_cards(title,zone_name,public_slug)').order('created_at', { ascending: false }); if (queryError) setError(queryError.message); else setOrders((data || []) as Order[]); setLoading(false); })(); }, []);
  return <div className="space-y-6"><header><p className="text-[11px] font-black uppercase tracking-[.2em] text-neon">Customer workspace</p><h1 className="text-3xl font-black">My Community Ads</h1><p className="mt-1 text-sm text-[var(--text-muted)]">Track your reserved spaces and completed local mailer placements.</p></header>{loading ? <p className="flex gap-2 text-sm text-[var(--text-muted)]"><Loader2 className="h-4 w-4 animate-spin" /> Loading placements…</p> : error ? <AdpadzCard className="border-red-400/30 p-4 text-sm text-red-200">{error}</AdpadzCard> : orders.length ? <div className="grid gap-4 md:grid-cols-2">{orders.map(order => <AdpadzCard key={order.id} className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-black">{order.community_cards?.title || 'Community card'}</p><p className="mt-1 flex items-center gap-1 text-xs text-[var(--text-muted)]"><MapPin className="h-3 w-3" />{order.community_cards?.zone_name || 'Mailing zone'}</p></div><span className="rounded-full border border-neon/30 bg-neon/10 px-2.5 py-1 text-[10px] font-black uppercase text-neon">{order.status.replace(/_/g, ' ')}</span></div><div className="mt-4 flex items-end justify-between"><p className="text-sm text-[var(--text-muted)]">{order.quantity} space{order.quantity > 1 ? 's' : ''} · {formatCurrency(order.amount_cents)}</p>{order.community_cards && <Link className="inline-flex items-center gap-1 text-sm font-black text-neon" to={`/community-cards/${order.community_cards.public_slug}`}>View card <ArrowRight className="h-4 w-4" /></Link>}</div></AdpadzCard>)}</div> : <AdpadzCard className="p-10 text-center"><ShoppingBag className="mx-auto h-8 w-8 text-neon" /><h2 className="mt-3 text-lg font-black">No community ad spaces yet</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Choose a live mailing zone to reserve one or two spaces for your business.</p><AdpadzButton className="mt-5" href="/">Explore Adpadz</AdpadzButton></AdpadzCard>}</div>;
}
