import { useEffect, useMemo, useState } from 'react';
import { ExternalLink, Loader2, Plus, Printer, Send, Settings2 } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { AdpadzButton, AdpadzCard } from '../../components/adpadz-ui';
import { COMMUNITY_CARD_LAYOUTS, formatCommunityCardFormat, formatCurrency, getCommunityCardLayout, type CommunityCardFormat, type CommunityCardRecord, type CommunityCardSlotRecord } from '../../lib/communityCards';

const input = 'input-field w-full';
export default function CommunityCards() {
  const [cards, setCards] = useState<CommunityCardRecord[]>([]); const [slots, setSlots] = useState<CommunityCardSlotRecord[]>([]); const [selected, setSelected] = useState<string>();
  const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [creating, setCreating] = useState(false);
  const [newCard, setNewCard] = useState({ title: '', zone: '', format: 'postcard_9x12' as CommunityCardFormat, homes: '5000' });
  const card = cards.find(item => item.id === selected); const cardSlots = useMemo(() => slots.filter(slot => slot.community_card_id === card?.id), [slots, card]);
  const sold = cardSlots.filter(s => s.status !== 'available').length;
  async function load() { setLoading(true); const { data: auth } = await supabase.auth.getUser(); if (!auth.user) { setMessage('Sign in to access the operator workspace.'); setLoading(false); return; }
    const { data: nextCards, error } = await supabase.from('community_cards').select('*').order('updated_at', { ascending: false });
    if (error) setMessage(error.message); const records = (nextCards || []) as CommunityCardRecord[]; setCards(records); setSelected(current => current && records.some(c => c.id === current) ? current : records[0]?.id);
    if (records.length) { const { data } = await supabase.from('community_card_slots').select('*').in('community_card_id', records.map(c => c.id)); setSlots((data || []) as CommunityCardSlotRecord[]); } else setSlots([]); setLoading(false);
  }
  useEffect(() => { void load(); }, []);
  async function createCard() { if (!newCard.title.trim()) return setMessage('Enter a card name.'); setCreating(true); setMessage(''); const { data: auth } = await supabase.auth.getUser(); const layout = COMMUNITY_CARD_LAYOUTS.find(item => item.format === newCard.format)!;
    const { data: created, error } = await supabase.from('community_cards').insert({ owner_id: auth.user!.id, title: newCard.title.trim(), zone_name: newCard.zone.trim() || null, market_name: newCard.zone.trim() || null, format: newCard.format, layout_key: layout.key, household_count: Number(newCard.homes) || null }).select('*').single();
    if (error || !created) { setMessage(error?.message || 'Could not create card.'); setCreating(false); return; }
    const { error: slotError } = await supabase.from('community_card_slots').insert(layout.slots.map(slot => ({ ...slot, community_card_id: created.id })));
    setCreating(false); if (slotError) setMessage(slotError.message); else { setMessage('Card created. Set the mailing zone, then publish when sales are ready.'); await load(); setSelected(created.id); }
  }
  async function updateCard(values: Partial<CommunityCardRecord>) { if (!card) return; const { data, error } = await supabase.from('community_cards').update(values).eq('id', card.id).select('*').single(); if (error || !data) return setMessage(error?.message || 'Could not save card.'); setCards(list => list.map(item => item.id === card.id ? data as CommunityCardRecord : item)); setMessage('Changes saved.'); }
  async function updateSlot(slot: CommunityCardSlotRecord, values: Partial<CommunityCardSlotRecord>) { const { data, error } = await supabase.from('community_card_slots').update(values).eq('id', slot.id).select('*').single(); if (error || !data) return setMessage(error?.message || 'Could not update slot.'); setSlots(list => list.map(item => item.id === slot.id ? data as CommunityCardSlotRecord : item)); }
  return <div className="space-y-6 print:space-y-0">
    <style>{`@media print { body * { visibility:hidden } #community-print, #community-print * { visibility:visible } #community-print {position:absolute;inset:0} .no-print{display:none!important} }`}</style>
    <header className="no-print flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-[11px] font-black uppercase tracking-[.2em] text-neon">Operator workspace</p><h1 className="text-3xl font-black">Community Card Manager</h1><p className="mt-1 text-sm text-[var(--text-muted)]">Fixed 2.75″ × 3.5″ inventory · $250 per space · $500 for two spaces.</p></div><AdpadzButton onClick={() => document.getElementById('new-card')?.scrollIntoView({ behavior: 'smooth' })}><Plus className="h-4 w-4" /> New mailing zone</AdpadzButton></header>
    {message && <AdpadzCard className="no-print border-neon/30 bg-neon/10 p-3 text-sm text-neon">{message}</AdpadzCard>}
    <AdpadzCard id="new-card" className="no-print p-5"><p className="text-sm font-black">Create a card for a mailing zone</p><div className="mt-4 grid gap-3 md:grid-cols-4"><label><span>Card name</span><input className={input} value={newCard.title} onChange={e => setNewCard(x => ({ ...x, title: e.target.value }))} placeholder="August Community Card" /></label><label><span>Mailing zone</span><input className={input} value={newCard.zone} onChange={e => setNewCard(x => ({ ...x, zone: e.target.value }))} placeholder="Englewood · Zone 3" /></label><label><span>Format</span><select className={input} value={newCard.format} onChange={e => setNewCard(x => ({ ...x, format: e.target.value as CommunityCardFormat }))}><option value="postcard_9x12">9×12 postcard · 16 spaces</option><option value="community_card_6x11">6×11 card · 8 spaces</option></select></label><label><span>Homes</span><input className={input} type="number" value={newCard.homes} onChange={e => setNewCard(x => ({ ...x, homes: e.target.value }))} /></label></div><div className="mt-4 flex justify-end"><AdpadzButton onClick={() => void createCard()} disabled={creating}>{creating && <Loader2 className="h-4 w-4 animate-spin" />}{creating ? 'Creating…' : 'Create fixed layout'}</AdpadzButton></div></AdpadzCard>
    {loading ? <p className="text-sm text-[var(--text-muted)]">Loading inventory…</p> : !card ? <AdpadzCard className="p-10 text-center text-sm text-[var(--text-muted)]">Create the first mailing zone to begin selling ad spaces.</AdpadzCard> : <>
      <div className="no-print flex gap-2 overflow-x-auto pb-1">{cards.map(item => <button key={item.id} onClick={() => setSelected(item.id)} className={`min-w-56 rounded-2xl border p-3 text-left ${item.id === card.id ? 'border-neon bg-neon/10' : 'border-white/10 bg-white/[.03]'}`}><b>{item.title}</b><span className="mt-1 block text-xs text-[var(--text-muted)]">{item.zone_name || 'Zone pending'} · {formatCommunityCardFormat(item.format)}</span></button>)}</div>
      <section className="no-print grid gap-4 lg:grid-cols-[1fr_auto]"><AdpadzCard className="p-5"><div className="grid gap-3 sm:grid-cols-3"><label><span>Card name</span><input className={input} defaultValue={card.title} onBlur={e => e.target.value !== card.title && void updateCard({ title: e.target.value })} /></label><label><span>Mailing zone</span><input className={input} defaultValue={card.zone_name || ''} onBlur={e => void updateCard({ zone_name: e.target.value || null, market_name: e.target.value || null })} /></label><label><span>Mailing date</span><input className={input} type="date" defaultValue={card.mailing_date || ''} onBlur={e => void updateCard({ mailing_date: e.target.value || null })} /></label></div><div className="mt-4 flex flex-wrap gap-2"><AdpadzButton variant="secondary" onClick={() => void updateCard({ is_published: !card.is_published, status: card.is_published ? 'draft' : 'selling' })}><Send className="h-4 w-4" /> {card.is_published ? 'Unpublish booking page' : 'Publish booking page'}</AdpadzButton><AdpadzButton variant="secondary" onClick={() => void updateCard({ sales_open: !card.sales_open })}><Settings2 className="h-4 w-4" /> {card.sales_open ? 'Close sales' : 'Open sales'}</AdpadzButton></div></AdpadzCard><div className="flex flex-wrap gap-2"><a className="inline-flex items-center gap-2 rounded-xl border border-neon/40 px-4 py-2 text-sm font-black text-neon" href={`/community-cards/${card.public_slug}`} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4" /> Customer view</a><button className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-4 py-2 text-sm font-black" onClick={() => window.print()}><Printer className="h-4 w-4" /> Export PDF</button></div></section>
      <section className="no-print grid gap-3 sm:grid-cols-3"><Metric label="Sold / held" value={`${sold} / ${cardSlots.length}`} /><Metric label="Inventory value" value={formatCurrency(cardSlots.length * 25000)} /><Metric label="Live booking" value={card.is_published && card.sales_open ? 'Open' : 'Closed'} /></section>
      <section id="community-print" className="grid gap-5 xl:grid-cols-2">{(['front','back'] as const).map(side => <CardCanvas key={side} card={card} slots={cardSlots} side={side} admin onUpdate={updateSlot} />)}</section>
      <AdpadzCard className="no-print p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black">Placement controls</p><p className="mt-1 text-xs text-[var(--text-muted)]">Add the final advertiser name and artwork URL here. A sold or reserved placement is immediately visible on the customer booking page.</p></div><span className="text-xs font-black text-neon">Fixed price: $250 / space</span></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{cardSlots.map(slot => <PlacementControl key={slot.id} slot={slot} onSave={values => updateSlot(slot, values)} />)}</div></AdpadzCard>
    </>}
  </div>;
}
export function CardCanvas({ card, slots, side, admin = false, onUpdate }: { card: CommunityCardRecord; slots: CommunityCardSlotRecord[]; side: 'front'|'back'; admin?: boolean; onUpdate?: (slot: CommunityCardSlotRecord, values: Partial<CommunityCardSlotRecord>) => Promise<void> }) { const template = getCommunityCardLayout(card.layout_key); const current = new Map(slots.map(slot => [slot.slot_key, slot])); return <div className="overflow-hidden rounded-2xl border border-neon/30 bg-[#f5f0df] p-2 text-[#1a1a1a]"><div className={`relative overflow-hidden border-[6px] border-[#1d4378] ${template.format === 'postcard_9x12' ? 'aspect-[1.5/1]' : 'aspect-[1.83/1]'}`}><div className="absolute left-0 right-0 top-[2%] h-[23%] bg-[#193d73] px-4 pt-2 text-center text-white"><p className="text-[8px] font-black uppercase tracking-[.18em]">{card.zone_name || card.market_name || 'Your neighborhood'}</p><h2 className="text-sm font-black uppercase">{card.title}</h2><p className="text-[8px] font-bold text-[#b6ff00]">Local shops. Local deals. One shared mailing zone.</p></div>{side === 'back' && <div className="absolute right-[4%] top-[27%] h-[12%] w-[25%] border border-black/30 bg-white p-1 text-[6px]">US POSTAGE / MAIL PANEL<br/>Local Postal Customer</div>}{template.slots.filter(s => s.side === side).map(t => { const slot = current.get(t.slot_key); const taken = slot && slot.status !== 'available'; return <button type="button" key={t.slot_key} disabled={!admin} onClick={() => admin && slot && void onUpdate?.(slot, { status: slot.status === 'available' ? 'reserved' : 'available', advertiser_name: slot.status === 'available' ? 'Sample local business' : null, ad_image_url: slot.status === 'available' ? 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=600&q=80' : null })} className={`absolute overflow-hidden border-2 text-left ${taken ? 'border-[#b6ff00] bg-black text-white' : 'border-white/80 bg-[#334f82] text-white'} ${admin ? 'cursor-pointer hover:ring-2 hover:ring-[#b6ff00]' : 'cursor-default'}`} style={{ left: `${t.x}%`, top: `${t.y}%`, width: `${t.width}%`, height: `${t.height}%` }}>{taken && slot?.ad_image_url ? <img src={slot.ad_image_url} alt={`${slot.advertiser_name || 'Purchased'} ad`} className="h-full w-full object-cover" /> : <span className="flex h-full flex-col items-center justify-center p-1 text-center"><b className="text-[8px]">{taken ? slot?.advertiser_name : 'AVAILABLE'}</b><small className="mt-1 text-[7px]">2.75″ × 3.5″ · $250</small></span>}</button>})}</div><p className="mt-2 text-center text-xs font-black uppercase tracking-[.18em] text-[#1d4378]">{side} · {formatCommunityCardFormat(card.format)}</p></div> }
function Metric({ label, value }: { label: string; value: string }) { return <AdpadzCard className="p-4"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[var(--text-muted)]">{label}</p><p className="mt-1 text-2xl font-black text-neon">{value}</p></AdpadzCard>; }
function PlacementControl({ slot, onSave }: { slot: CommunityCardSlotRecord; onSave: (values: Partial<CommunityCardSlotRecord>) => Promise<void> }) { const [name, setName] = useState(slot.advertiser_name || ''); const [image, setImage] = useState(slot.ad_image_url || ''); const [status, setStatus] = useState(slot.status); return <div className="rounded-xl border border-white/10 bg-black/15 p-3"><div className="mb-2 flex justify-between gap-3"><b className="text-sm">{slot.label}</b><select className="rounded border border-white/10 bg-black px-2 text-xs" value={status} onChange={e => { const next = e.target.value as CommunityCardSlotRecord['status']; setStatus(next); void onSave({ status: next, advertiser_name: next === 'available' ? null : name || null, ad_image_url: next === 'available' ? null : image || null }); }}><option value="available">Available</option><option value="reserved">Reserved</option><option value="sold">Sold</option><option value="proof">Proof</option><option value="approved">Approved</option></select></div><input className={input} value={name} onChange={e => setName(e.target.value)} onBlur={() => void onSave({ advertiser_name: name || null })} placeholder="Advertiser name" /><input className={`${input} mt-2`} value={image} onChange={e => setImage(e.target.value)} onBlur={() => void onSave({ ad_image_url: image || null })} placeholder="Creative image URL" /></div>; }
