import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, CheckCircle2, Lock, ShoppingBag } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { AdpadzButton, AdpadzCard } from '../components/adpadz-ui';
import { CardCanvas } from './business/CommunityCards';
import { formatCurrency, slotPrice, type CommunityCardRecord, type CommunityCardSlotRecord } from '../lib/communityCards';

export default function CommunityCardPublic() {
  const { slug } = useParams(); const [card, setCard] = useState<CommunityCardRecord>(); const [slots, setSlots] = useState<CommunityCardSlotRecord[]>([]); const [selected, setSelected] = useState<string[]>([]); const [message, setMessage] = useState('');
  useEffect(() => { void (async () => { const { data: c, error } = await supabase.from('community_cards').select('*').eq('public_slug', slug).eq('is_published', true).single(); if (error || !c) return setMessage('This community card is not currently available.'); setCard(c as CommunityCardRecord); const { data: s } = await supabase.from('community_card_slots').select('*').eq('community_card_id', c.id); setSlots((s || []) as CommunityCardSlotRecord[]); })(); }, [slug]);
  const available = useMemo(() => slots.filter(s => s.status === 'available'), [slots]);
  function toggle(slot: CommunityCardSlotRecord) { if (slot.status !== 'available') return; setSelected(current => current.includes(slot.id) ? current.filter(id => id !== slot.id) : current.length === 2 ? current : [...current, slot.id]); }
  async function reserve() { if (!card || !selected.length) return; const { data } = await supabase.auth.getUser(); if (!data.user) { window.location.href = `/auth?next=${encodeURIComponent(`/community-cards/${slug}`)}`; return; }
    const { error } = await supabase.rpc('reserve_community_card_spaces', { p_card_id: card.id, p_slot_ids: selected });
    if (error) return setMessage(error.message); setMessage('Your space is held. Checkout will be enabled when the secure payment connection is activated.'); setSelected([]); const { data: fresh } = await supabase.from('community_card_slots').select('*').eq('community_card_id', card.id); setSlots((fresh || []) as CommunityCardSlotRecord[]);
  }
  if (message && !card) return <main className="grid min-h-screen place-items-center bg-[var(--bg-base)] p-6 text-center text-white"><AdpadzCard className="max-w-md p-8"><h1 className="text-xl font-black">Community Card</h1><p className="mt-2 text-sm text-[var(--text-muted)]">{message}</p></AdpadzCard></main>;
  if (!card) return <main className="grid min-h-screen place-items-center bg-[var(--bg-base)] text-sm text-[var(--text-muted)]">Loading community card…</main>;
  return <main className="min-h-screen bg-[var(--bg-base)] px-4 py-8 text-white sm:px-8"><div className="mx-auto max-w-7xl"><header className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-[11px] font-black uppercase tracking-[.2em] text-neon">Adpadz community appreciation card</p><h1 className="mt-1 text-3xl font-black">{card.title}</h1><p className="mt-2 text-sm text-[var(--text-muted)]">{card.zone_name || card.market_name} · {available.length} spaces still available</p></div><Link to="/"><span className="font-black text-neon">adpadz.co</span></Link></header><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_330px]"><section className="grid gap-5 lg:grid-cols-2"><CardCanvas card={card} slots={slots} side="front" /><CardCanvas card={card} slots={slots} side="back" /></section><aside><AdpadzCard className="sticky top-5 p-5"><div className="flex items-center gap-2 text-neon"><ShoppingBag className="h-5 w-5" /><b>Choose your ad space</b></div><p className="mt-2 text-sm text-[var(--text-muted)]">Purchased ads stay visible here, so you can see the businesses joining your mailing zone. Only open spaces can be selected.</p><div className="mt-4 max-h-72 space-y-2 overflow-auto">{slots.map(slot => { const chosen = selected.includes(slot.id); const open = slot.status === 'available'; return <button key={slot.id} disabled={!open} onClick={() => toggle(slot)} className={`flex w-full items-center justify-between rounded-xl border p-3 text-left text-sm ${chosen ? 'border-neon bg-neon/15' : open ? 'border-white/15 hover:border-neon/50' : 'cursor-not-allowed border-white/5 bg-white/[.03] opacity-55'}`}><span><b>{open ? slot.label : slot.advertiser_name || 'Purchased ad space'}</b><small className="mt-1 block text-xs text-[var(--text-muted)]">{open ? '2.75″ × 3.5″' : 'Filled'}</small></span>{open ? chosen ? <CheckCircle2 className="h-5 w-5 text-neon" /> : <span className="font-black text-neon">$250</span> : <Lock className="h-4 w-4" />}</button>})}</div><div className="mt-5 border-t border-white/10 pt-4"><div className="flex justify-between text-sm"><span>{selected.length} of 2 spaces selected</span><b className="text-neon">{formatCurrency(slotPrice(selected.length))}</b></div><p className="mt-1 text-xs text-[var(--text-muted)]">One space is $250. Two spaces are $500 firm.</p><AdpadzButton fullWidth className="mt-3" disabled={!selected.length || !card.sales_open} onClick={() => void reserve()}>{card.sales_open ? <>Continue to checkout <ArrowRight className="h-4 w-4" /></> : 'Sales are currently closed'}</AdpadzButton>{message && <p className="mt-3 text-xs text-neon">{message}</p>}</div></AdpadzCard></aside></div></div></main>;
}
